#import <Foundation/Foundation.h>
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGConversionsApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGConversionsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGConversionsApi*) sharedAPI;
///
///
/// Get all conversions
/// This endpoint provides a list of all conversions performed by a business.
///
/// @param businessId This could be the ID of the business or the ID of a sub-account of the business
/// 
///
/// @return 
-(NSNumber*) getallconversionsWithCompletionBlock :(NSString*) businessId 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// Initiate a conversion
/// This endpoint provides information on the conversion rate between two currencies e.g NGN to USD\n\n\n\n\nREQUEST BODY\n\n\n| Field | Data Type | Description |\n|------| ------------- | ----------- |\n| business | string | This could be the ID of the business or the ID of a sub-account of the businessRequired |\n| quoteReference | string | To get a quote reference, you will need to call the generate quote endpoint Required |
///
/// 
///
/// @return 
-(NSNumber*) initiateaconversionWithCompletionBlock :
    
    (void (^)(NSError* error))completionBlock;


///
///
/// Get a conversion
/// This endpoint fetches a specific conversion performed by a business.
///
/// @param conversionId The ID of the conversion
/// 
///
/// @return 
-(NSNumber*) getaconversionWithCompletionBlock :(NSString*) conversionId 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;



@end
