#import <Foundation/Foundation.h>
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGCoreApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGCoreApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGCoreApi*) sharedAPI;
///
///
/// Get Bank code
/// This endpoint provides a list of the banks and mobile money wallet providers with information like name, code and the list of branches and branch codes per bank based on a specified currency.\n\nThe **code** field in the below sample refers to the bank code for your bank account or the code of your mobile money provider. \n\n```json\n{\n {\n   \"id\": 147,\n   \"code\": \"GH010100\",\n   \"name\": \"BANK OF GHANA\",\n   \"isMobileVerified\": null,\n   \"branches\": [\n      {\n        \"id\": 1,\n        \"branchCode\": \"GH010101\",\n        \"branchName\": \"BANK OF GHANA-ACCRA\",\n        \"swiftCode\": \"BAGHGHAC\",\n        \"bic\": \"BAGHGHAC\"\n       }]\n },\n {\n  \"id\": 79,\n  \"code\": \"AIRTEL\",\n  \"name\": \"Airtel\",\n  \"isMobileVerified\": true,\n  \"branches\": null\n }\n}\n```
///
/// @param currency e.g NGN, GHS, KES
/// 
///
/// @return 
-(NSNumber*) getBankcodeWithCompletionBlock :(NSString*) currency 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// Get branch Code
/// This endpoint provides a list of the branches for a bank and helps you get your branch code. To get a branch Code: \n+ Make a request to the endpoint that provides bank code with your desired currency \n+ Find your bank in the list returned.\n+ Check the id field of your bank information for your branch\n+ use the id field to make a request to this endpoint to get the list of branches for your bank\n+ Check the **branchCode** field of your branch information for the value of your branch code
///
/// @param bankId Id of the bank
/// 
///
/// @return 
-(NSNumber*) getbranchCodeWithCompletionBlock :(NSString*) bankId 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// Get a disbursement transaction by customer reference
/// This endpoint provides the details of a disbursement transaction through the use of a customer reference.
///
/// @param business The ID of the business
/// @param customerReference The reference of the customer/merchant
/// 
///
/// @return 
-(NSNumber*) getadisbursementtransactionbycustomerreferenceWithCompletionBlock :(NSString*) business 
     customerReference:(NSString*) customerReference 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// Get a disbursement transaction by reference
/// This endpoint provides the details of a disbursement transaction through the use of its reference.
///
/// @param business The ID of business
/// @param reference The reference of the transaction
/// 
///
/// @return 
-(NSNumber*) getadisbursementtransactionbyreferenceWithCompletionBlock :(NSString*) business 
     reference:(NSString*) reference 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// Get the transactions for a Business
/// This endpoint provides a list of all the transactions for a business.\n\n\nREQUEST BODY\n\n\n| Field | Data Type | Description |\n|------| ------------- | ----------- |\n| page | string | Specify exactly what page you want to retrieve optional|\n| perPage | string | Specify how many records you want to retrieve per page optional|\n| from | string| Specify start date with format \"YYYY-mm-dd\"  optional|\n| to | string| Specify end date with format \"YYYY-mm-dd\" optional|
///
/// @param businessID This could be the ID of the business or the ID of a sub-account of the business
/// 
///
/// @return 
-(NSNumber*) getthetransactionsforaBusinessWithCompletionBlock :(NSString*) businessID 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// Get the transactions for the sub-accounts of a Business
/// This provides a list of all the transactions for the sub-accounts of a Business.\n\n\nREQUEST BODY\n\n\n| Field | Data Type | Description |\n|------| ------------- | ----------- |\n| page | string | Specify exactly what page you want to retrieve optional|\n| perPage | string | Specify how many records you want to retrieve per page optional|\n| from | string| Specify start date with format \"YYYY-mm-dd\"  optional|\n| to | string| Specify end date with format \"YYYY-mm-dd\" optional|
///
/// @param businessID The is the ID of a business
/// 
///
/// @return 
-(NSNumber*) getthetransactionsforthesubAccountsofabusinessWithCompletionBlock :(NSString*) businessID 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;


///
///
/// Get a transaction for a business
/// This endpoint provides the details of a transaction through the use of its ID.
///
/// @param transactionID The reference or ID of the transaction
/// 
///
/// @return 
-(NSNumber*) getatransactionforabusinessWithCompletionBlock :(NSString*) transactionID 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;



@end
