#import <Foundation/Foundation.h>
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGQuotesApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGQuotesApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGQuotesApi*) sharedAPI;
///
///
/// Get a quote
/// This endpoint is used for generating a quote.\n\nREQUEST BODY\n\n\n| Field | Data Type | Description |\n|------| ------------- | ----------- |\n| sourceCurrency | string | e.g _USD_ required|\n| destinationCurrency | string |  e.g _NGN_ required|\n| amount | string | required|\n| action | string | the values can be either \"_send_\" for conversions and disbursement or \"_receive_\" for collectionsrequired|\n| transactionType | string | the values here can be either _disbursement_ or _collection_ or _conversion_required |\n| business | string | This could be the ID of the business or the ID of a sub-account of the business required|\n| feeBearer | string | required  |\n| paymentDestination | string | See the note below |\n| paymentMethod | string | see the note below |\n| destinationCountry | string | This is the location where the money would be received required |\n| paymentScheme | string | This is the valid payment scheme for the destination currency you want to generate a quote for.Payment scheme is required for USD,EUR and GBP |\n\nNOTE\n\nIf destination currency is either USD,EUR,GBP a payment scheme is required .\n\nThe values of the _paymentDestination_ and _paymentMethod_ are either required or optional depending on the value of the _transactiontype_ field.\n\nWhen the value of the the _transactiontype_ field is _disbursement_, We will then have the below fields as:\n*   paymentDestination required\n*   paymentMethod optional\n\n\nWhen the value of the the _transactiontype_ field is _conversion_, We will then have the below fields as:\n*   paymentDestination optional\n*   paymentMethod optional\n\nWhen the value of the the _transactiontype_ field is _collection_, We will then have the below fields as:\n*   paymentDestination required\n*   paymentMethod required
///
/// 
///
/// @return 
-(NSNumber*) getaquoteWithCompletionBlock :
    
    (void (^)(NSError* error))completionBlock;



@end
