#import <Foundation/Foundation.h>
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGResolveApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGResolveApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGResolveApi*) sharedAPI;
///
///
/// Resolve Bank Account
/// This endpoint resolves bank account information based the account number and bank code provided. This is only valid for Nigerian bank accounts
///
/// 
///
/// @return 
-(NSNumber*) resolveBankAccountWithCompletionBlock :
    
    (void (^)(NSError* error))completionBlock;



@end
